version: 2
updates:
- package-ecosystem: npm
  directory: "/desktop"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - ThomasGaubert
  assignees:
  - ThomasGaubert
  ignore:
  - dependency-name: webpack
    versions:
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: electron
    versions:
    - 11.2.1
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: socket.io
    versions:
    - 2.4.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
    - 17.0.3
  - dependency-name: react-is
    versions:
    - 17.0.1
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.4.1
  - dependency-name: csp-html-webpack-plugin
    versions:
    - 5.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: react-redux
    versions:
    - 7.2.2
  - dependency-name: ts-loader
    versions:
    - 8.0.14
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - ThomasGaubert
  ignore:
  - dependency-name: com.google.dagger:dagger
    versions:
    - "2.33"
    - "2.34"
    - 2.34.1
    - "2.35"
  - dependency-name: com.google.dagger:dagger-compiler
    versions:
    - 2.31.2
    - "2.32"
    - "2.33"
    - "2.34"
    - 2.34.1
    - "2.35"
  - dependency-name: com.facebook.flipper:flipper
    versions:
    - 0.75.1
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.79.1
    - 0.80.0
    - 0.81.0
    - 0.82.0
    - 0.82.1
    - 0.82.2
    - 0.83.0
    - 0.84.0
    - 0.85.0
  - dependency-name: com.facebook.flipper:flipper-network-plugin
    versions:
    - 0.75.1
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.79.1
    - 0.80.0
    - 0.81.0
    - 0.82.0
    - 0.82.1
    - 0.82.2
    - 0.83.0
    - 0.84.0
    - 0.85.0
  - dependency-name: androidx.window:window
    versions:
    - 1.0.0-alpha03
    - 1.0.0-alpha04
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
  - dependency-name: com.reddit:indicator-fast-scroll
    versions:
    - 1.4.0
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
  - dependency-name: io.socket:socket.io-client
    versions:
    - 2.0.0
  - dependency-name: com.google.firebase:firebase-config
    versions:
    - 20.0.3
  - dependency-name: com.google.firebase:firebase-ml-vision
    versions:
    - 24.1.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: com.google.firebase:firebase-perf
    versions:
    - 19.1.0
