version: 2
updates:
- package-ecosystem: npm
  directory: "/desktop"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 5
  reviewers:
  - ThomasGaubert
  assignees:
  - ThomasGaubert
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 5
  reviewers:
  - ThomasGaubert
  assignees:
  - ThomasGaubert