enum ActionTypeKeys {
  NAVIGATE_HOME = 'NAVIGATE_HOME',
  NAVIGATE_HISTORY = 'NAVIGATE_HISTORY',
  NAVIGATE_SETTINGS = 'NAVIGATE_SETTINGS',

  TOAST_SHOW = 'TOAST_SHOW',
  TOAST_HIDE = 'TOAST_HIDE',

  SERVER_CONNECT = 'SERVER_CONNECT',
  SERVER_CONNECTED = 'SERVER_CONNECTED',
  SERVER_DISCONNECT = 'SERVER_DISCONNECT',
  SERVER_ERROR = 'SERVER_ERROR',

  NOTIFICATION_POST = 'NOTIFICATION_POST',
  NOTIFICATION_DISMISS = 'NOTIFICATION_DISMISS'
}

export default ActionTypeKeys;
